# Generated by Django 5.1.7 on 2025-04-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('codigo_rol', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
