# Generated by Django 5.1.7 on 2025-04-05 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('cedula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='pregunta_seguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField(unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Preguntas de seguridad',
                'db_table': 'preguntas_seguridad',
            },
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('codigo_rol', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña_hash', models.CharField(max_length=128)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('codigo_rol', models.ForeignKey(db_column='codigo_rol', on_delete=django.db.models.deletion.PROTECT, to='login.rol')),
                ('empleado', models.ForeignKey(db_column='empleado_cedula', on_delete=django.db.models.deletion.CASCADE, to='login.empleado')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='usuario_pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_hash', models.CharField(max_length=128)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pregunta', models.ForeignKey(db_column='pregunta_id', on_delete=django.db.models.deletion.PROTECT, to='login.pregunta_seguridad')),
                ('usuario', models.ForeignKey(db_column='usuario_cedula', on_delete=django.db.models.deletion.CASCADE, to='login.usuario')),
            ],
            options={
                'verbose_name': 'Pregunta de usuario',
                'verbose_name_plural': 'Preguntas de usuarios',
                'db_table': 'usuario_preguntas',
                'unique_together': {('usuario', 'pregunta')},
            },
        ),
    ]
