# Generated by Django 5.1.7 on 2025-04-05 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_usuario_codigo_rol_usuario_rol'),
    ]

    operations = [
    ]
