# Generated by Django 5.1.7 on 2025-04-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20250405_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='tipo_identificacion',
            field=models.CharField(choices=[('V', 'Venezolano'), ('E', 'Extranjero'), ('P', 'Pasaporte')], default='V', max_length=1),
            preserve_default=False,
        ),
    ]
