# Generated by Django 5.1.7 on 2025-04-14 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_empleado_tipo_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_pregunta',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='login.usuario'),
        ),
    ]
