# Generated by Django 5.1.7 on 2025-04-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_usuario_pregunta_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='codigo_rol',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
