# Generated by Django 5.1.7 on 2025-05-08 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_rol_codigo_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_pregunta',
            name='pregunta',
            field=models.ForeignKey(db_column='pregunta_id', on_delete=django.db.models.deletion.CASCADE, to='login.pregunta_seguridad'),
        ),
    ]
