# Generated by Django 5.1.7 on 2025-05-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_usuario_pregunta_pregunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='meses_año',
            fields=[
                ('id_mes', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_mes', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'mes_del_anio',
                'ordering': ['id_mes'],
            },
        ),
        migrations.CreateModel(
            name='TipoNomina',
            fields=[
                ('codigo_tiponomina', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tipo_nomina', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_nomina',
            },
        ),
    ]
