# Generated by Django 5.1.7 on 2025-05-11 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_meses_año_tiponomina'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoNomina',
            new_name='tipo_nomina',
        ),
    ]
