# Generated by Django 5.1.7 on 2025-05-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_rename_tiponomina_tipo_nomina'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='meses_año',
            new_name='meses',
        ),
        migrations.AlterModelTable(
            name='meses',
            table='meses',
        ),
    ]
