# Generated by Django 5.1.7 on 2025-05-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_rename_meses_año_meses_alter_meses_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='secuencia',
            fields=[
                ('id_secuencia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_secuencia', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'secuencia',
                'ordering': ['id_secuencia'],
            },
        ),
    ]
