# Generated by Django 5.1.7 on 2025-05-13 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_secuencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='concepto_pago',
            fields=[
                ('id_conceptopago', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('nombre_nomina', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_pago',
            fields=[
                ('codigo_tipopago', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tipopago', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_trabajador',
            fields=[
                ('codigo_trabajador', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mes_aplicacionconcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conceptopago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.concepto_pago')),
                ('meses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.meses')),
            ],
        ),
        migrations.AddField(
            model_name='concepto_pago',
            name='tipo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.tipo_pago'),
        ),
        migrations.CreateModel(
            name='concepto_tipotrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conceptopago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.concepto_pago')),
                ('tipo_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.tipo_trabajador')),
            ],
        ),
    ]
