# Generated by Django 5.1.7 on 2025-05-13 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_concepto_pago_tipo_pago_tipo_trabajador_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='concepto_pago',
            table='concepto_pago',
        ),
        migrations.AlterModelTable(
            name='concepto_tipotrabajador',
            table='concepto_tipotrabajador',
        ),
        migrations.AlterModelTable(
            name='mes_aplicacionconcepto',
            table='mes_aplicacionconcepto',
        ),
        migrations.AlterModelTable(
            name='tipo_pago',
            table='tipo_pago',
        ),
        migrations.AlterModelTable(
            name='tipo_trabajador',
            table='tipo_trabajador',
        ),
    ]
