# Generated by Django 5.1.7 on 2025-05-14 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_alter_concepto_pago_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepto_pago',
            name='id_conceptopago',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='nomina',
            fields=[
                ('id_nomina', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('periodo', models.CharField(max_length=255)),
                ('secuencia', models.CharField(max_length=20)),
                ('fecha_cierre', models.DateField()),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('tipo_nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.tipo_nomina')),
            ],
            options={
                'db_table': 'nomina',
            },
        ),
    ]
