# Generated by Django 5.1.7 on 2025-05-14 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_alter_concepto_pago_id_conceptopago_nomina'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('total_bruto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_deducciones', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pdf', models.FileField(upload_to='recibos/')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.nomina')),
            ],
            options={
                'verbose_name': 'Recibo de Pago',
                'verbose_name_plural': 'Recibos de Pago',
            },
        ),
    ]
