# Generated by Django 5.1.7 on 2025-05-14 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_recibopago'),
    ]

    operations = [
        migrations.CreateModel(
            name='recibo_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pdf', models.FileField(upload_to='recibos/')),
                ('id_conceptopago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.concepto_pago')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.nomina')),
            ],
            options={
                'verbose_name': 'Recibo de Pago',
                'verbose_name_plural': 'Recibos de Pago',
                'db_table': 'recibo_pago',
            },
        ),
        migrations.DeleteModel(
            name='ReciboPago',
        ),
    ]
