# Generated by Django 5.1.7 on 2025-05-15 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_recibo_pago_delete_recibopago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recibo_pago',
            options={},
        ),
        migrations.RenameField(
            model_name='concepto_tipotrabajador',
            old_name='id_conceptopago',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='mes_aplicacionconcepto',
            old_name='id_conceptopago',
            new_name='codigo',
        ),
        migrations.RemoveField(
            model_name='concepto_pago',
            name='id_conceptopago',
        ),
        migrations.RemoveField(
            model_name='recibo_pago',
            name='id_conceptopago',
        ),
        migrations.RemoveField(
            model_name='recibo_pago',
            name='monto',
        ),
        migrations.AlterField(
            model_name='concepto_pago',
            name='codigo',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='secuencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.secuencia'),
        ),
        migrations.AlterField(
            model_name='recibo_pago',
            name='cedula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.empleado'),
        ),
        migrations.AlterField(
            model_name='recibo_pago',
            name='nomina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.nomina'),
        ),
        migrations.AlterField(
            model_name='recibo_pago',
            name='pdf',
            field=models.FileField(upload_to='recibos/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='detalle_nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pdf', models.FileField(upload_to='recibos/')),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.empleado')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.concepto_pago')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.nomina')),
            ],
            options={
                'verbose_name': 'Detalle de Nomina',
                'verbose_name_plural': 'Detalles de Nomina',
                'db_table': 'detalle_nomina',
            },
        ),
        migrations.CreateModel(
            name='detalle_recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_nomina', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='login.detalle_nomina')),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.recibo_pago')),
            ],
            options={
                'db_table': 'detalle_recibo',
            },
        ),
    ]
