# Generated by Django 5.1.7 on 2025-05-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_alter_recibo_pago_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_pago',
            name='abreviatura_excel_tipopago',
            field=models.CharField(default='Ordinario', max_length=20),
            preserve_default=False,
        ),
    ]
