# Generated by Django 5.1.7 on 2025-05-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_tipo_pago_abreviatura_excel_tipopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='concepto_pago',
            name='tipo_concepto',
            field=models.CharField(choices=[('ASIGNACION', 'Asignación'), ('DEDUCCION', 'Deducción')], default='ASIGNACION', max_length=20),
            preserve_default=False,
        ),
    ]
