# Generated by Django 5.1.7 on 2025-05-19 13:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_concepto_pago_tipo_concepto'),
    ]

    operations = [
        migrations.CreateModel(
            name='banco',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bancos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargos',
                'ordering': ['familia', 'nivel__orden_jerarquico'],
            },
        ),
        migrations.CreateModel(
            name='nivel_cargo',
            fields=[
                ('nivel', models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V'), (6, 'VI'), (7, 'Jefe')], primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('orden_jerarquico', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Niveles de cargo',
                'db_table': 'niveles_cargo',
                'ordering': ['orden_jerarquico'],
            },
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['primer_apellido', 'primer_nombre'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='actualizado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='empleado',
            name='conyuge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('S', 'Soltero/a'), ('C', 'Casado/a'), ('D', 'Divorciado/a'), ('V', 'Viudo/a')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='grado_instruccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='hijos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empleado',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nss',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='rif',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono_principal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono_secundario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_trabajador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='login.tipo_trabajador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cargo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='login.cargo'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='familia_cargo',
            fields=[
                ('codigo_familiacargo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.tipo_trabajador')),
            ],
            options={
                'verbose_name_plural': 'Familias de cargo',
                'db_table': 'familias_cargo',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='login.familia_cargo'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='login.nivel_cargo'),
        ),
        migrations.CreateModel(
            name='cuenta_bancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'Corriente'), ('A', 'Ahorro')], default='C', max_length=1)),
                ('numero_cuenta', models.CharField(max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='login.banco')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='login.empleado')),
            ],
            options={
                'verbose_name_plural': 'Cuentas bancarias',
                'db_table': 'cuentas_bancarias',
                'unique_together': {('banco', 'numero_cuenta')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cargo',
            unique_together={('familia', 'nivel')},
        ),
    ]
