# Generated by Django 5.1.7 on 2025-05-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_banco_cargo_nivel_cargo_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
