# Generated by Django 5.1.7 on 2025-05-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_alter_empleado_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='nss',
        ),
    ]
