# Generated by Django 5.1.7 on 2025-05-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_remove_empleado_nss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia_cargo',
            name='codigo_familiacargo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
