# Generated by Django 5.1.7 on 2025-05-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_alter_familia_cargo_codigo_familiacargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel_cargo',
            name='nivel',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('JEFE', 'Jefe')], max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
