# Generated by Django 5.1.7 on 2025-05-19 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_alter_nivel_cargo_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibo_pago',
            name='pdf',
        ),
    ]
