# Generated by Django 5.1.7 on 2025-05-19 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_remove_recibo_pago_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_nomina',
            name='pdf',
        ),
    ]
