# Generated by Django 5.1.7 on 2025-05-19 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_remove_detalle_nomina_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_recibo',
            name='detalle_nomina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.detalle_nomina'),
        ),
    ]
