# Generated by Django 5.1.7 on 2025-05-19 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_alter_detalle_recibo_detalle_nomina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_recibo',
            name='recibo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='login.recibo_pago'),
        ),
        migrations.AlterUniqueTogether(
            name='detalle_recibo',
            unique_together={('recibo', 'detalle_nomina')},
        ),
    ]
