# Generated by Django 5.1.7 on 2025-05-21 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0029_alter_detalle_recibo_recibo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recibo_pago',
            options={'verbose_name': 'Recibo de Pago', 'verbose_name_plural': 'Recibos de Pago'},
        ),
    ]
