# Generated by Django 5.1.7 on 2025-05-22 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0030_alter_recibo_pago_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='prenomina',
            fields=[
                ('id_prenomina', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nomina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.nomina')),
            ],
            options={
                'verbose_name': 'Pre-Nómina',
                'verbose_name_plural': 'Pre-Nóminas',
                'db_table': 'prenomina',
            },
        ),
        migrations.CreateModel(
            name='detalle_prenomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.concepto_pago')),
                ('prenomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='login.prenomina')),
            ],
            options={
                'verbose_name': 'Detalle de Pre-Nómina',
                'verbose_name_plural': 'Detalles de Pre-Nómina',
                'db_table': 'detalle_prenomina',
                'unique_together': {('prenomina', 'codigo')},
            },
        ),
    ]
