# Generated by Django 5.1.7 on 2025-05-24 18:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0031_prenomina_detalle_prenomina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concepto_tipotrabajador',
            name='codigo',
        ),
        migrations.AddField(
            model_name='concepto_tipotrabajador',
            name='concepto',
            field=models.ForeignKey(db_column='codigo', default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='login.concepto_pago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='concepto_tipotrabajador',
            name='tipo_trabajador',
            field=models.ForeignKey(db_column='tipo_trabajador_id', on_delete=django.db.models.deletion.CASCADE, to='login.tipo_trabajador'),
        ),
    ]
