# Generated by Django 5.1.7 on 2025-05-29 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0033_permiso_rol_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol_permisos',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
