# Generated by Django 5.1.7 on 2025-05-30 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0034_rol_permisos_fecha_asignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='login.rol'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='usuario_rol',
        ),
    ]
