# Generated by Django 5.1.7 on 2025-06-05 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0035_usuario_rol_delete_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta_bancaria',
            name='numero_cuenta',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='detalle_nomina',
            name='nomina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.nomina'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rif',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recibo_pago',
            name='nomina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.nomina'),
        ),
    ]
