# Generated by Django 5.1.7 on 2025-06-11 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0037_usuario_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='nivel_salarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(choices=[('B', 'Bachiller'), ('T', 'Técnico Superior'), ('P', 'Profesional')], max_length=1)),
                ('nivel', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII')], max_length=3)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.tipo_trabajador')),
            ],
            options={
                'db_table': 'niveles_salariales',
                'unique_together': {('grado', 'nivel', 'tipo_trabajador')},
            },
        ),
    ]
