# Generated by Django 5.1.7 on 2025-06-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0038_nivel_salarial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel_salarial',
            name='grado',
            field=models.CharField(choices=[('BI', 'BI - Bachiller I'), ('BII', 'BII - Bachiller II'), ('BIII', 'BIII - Bachiller III'), ('TI', 'TI - Técnico I'), ('TII', 'TII - Técnico II'), ('PI', 'PI - Profesional I'), ('PII', 'PII - Profesional II'), ('PIII', 'PIII - Profesional III')], max_length=4),
        ),
    ]
