# Generated by Django 5.1.7 on 2025-06-11 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0039_alter_nivel_salarial_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='nivel_salarial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='login.nivel_salarial'),
        ),
    ]
