# Generated by Django 5.1.7 on 2025-06-11 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0040_empleado_nivel_salarial'),
    ]

    operations = [
        migrations.CreateModel(
            name='asistencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('A', 'Asistió'), ('F', 'Falta'), ('J', 'Falta Justificada'), ('V', 'Vacaciones'), ('P', 'Permiso'), ('L', 'Licencia')], default='A', max_length=1)),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='login.empleado')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.asistencias')),
            ],
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('M', 'Enfermedad'), ('P', 'Permiso'), ('O', 'Otro')], max_length=1)),
                ('descripcion', models.TextField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='justificaciones/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificaciones_aprobadas', to='login.empleado')),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificaciones', to='login.asistencias')),
            ],
            options={
                'verbose_name': 'Justificación de Falta',
                'verbose_name_plural': 'Justificaciones de Faltas',
                'db_table': 'justificaciones',
            },
        ),
    ]
