# Generated by Django 5.1.7 on 2025-06-11 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0041_asistencias_justificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='justificacion',
            old_name='asistencia',
            new_name='asistencias',
        ),
    ]
