# Generated by Django 5.1.7 on 2025-06-11 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0042_rename_asistencia_justificacion_asistencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MED', 'Médica'), ('MAT', 'Maternidad/Paternidad'), ('STU', 'Estudio')], max_length=3)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='licencias/')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='permiso_asistencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REM', 'Remunerado'), ('NREM', 'No Remunerado'), ('ESP', 'Especial')], max_length=4)),
                ('fecha', models.DateField()),
                ('horas', models.DecimalField(decimal_places=2, max_digits=4)),
                ('motivo', models.TextField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='registro_vacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias', models.PositiveIntegerField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='vacaciones/')),
                ('aprobado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_aprobadas', to='login.empleado')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.empleado')),
            ],
        ),
    ]
