# Generated by Django 5.1.7 on 2025-06-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0043_licencia_permiso_asistencias_registro_vacaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencias',
            name='horas_trabajadas',
        ),
        migrations.AddField(
            model_name='asistencias',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencias',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
