# Generated by Django 5.1.7 on 2025-06-12 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0044_remove_asistencias_horas_trabajadas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencias',
            options={'verbose_name': 'Asistencia del personal', 'verbose_name_plural': 'Asistencias del personal'},
        ),
        migrations.AlterModelTable(
            name='asistencias',
            table='asistencias',
        ),
    ]
