# Generated by Django 5.1.7 on 2025-06-12 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0045_alter_asistencias_options_alter_asistencias_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justificacion',
            name='aprobado',
        ),
    ]
