# Generated by Django 5.1.7 on 2025-06-13 15:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0046_remove_justificacion_aprobado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso_asistencias',
            options={'verbose_name_plural': 'Permisos_asistencias'},
        ),
        migrations.AlterModelOptions(
            name='registro_vacaciones',
            options={'ordering': ['-fecha_inicio'], 'verbose_name_plural': 'Registros de Vacaciones'},
        ),
        migrations.RemoveField(
            model_name='permiso_asistencias',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='permiso_asistencias',
            name='horas',
        ),
        migrations.RemoveField(
            model_name='permiso_asistencias',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='permiso_asistencias',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='registro_vacaciones',
            name='aprobado_por',
        ),
        migrations.RemoveField(
            model_name='registro_vacaciones',
            name='dias',
        ),
        migrations.RemoveField(
            model_name='registro_vacaciones',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='registro_vacaciones',
            name='empleado',
        ),
        migrations.AddField(
            model_name='permiso_asistencias',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobador', to='login.usuario'),
        ),
        migrations.AddField(
            model_name='permiso_asistencias',
            name='descriptcion',
            field=models.CharField(default='Permiso de asistencia', max_length=100),
        ),
        migrations.AddField(
            model_name='permiso_asistencias',
            name='fecha_fin',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='permiso_asistencias',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='registro_vacaciones',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registro_vacaciones',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='registro_vacaciones',
            name='dias_efectivos',
            field=models.PositiveIntegerField(default=0, help_text='Días realmente disfrutados'),
        ),
        migrations.AddField(
            model_name='registro_vacaciones',
            name='dias_habilitados',
            field=models.PositiveIntegerField(default=0, help_text='Días disponibles para usar'),
        ),
        migrations.AddField(
            model_name='registro_vacaciones',
            name='dias_planificados',
            field=models.PositiveIntegerField(default=0, verbose_name='Días planificados de vacaciones'),
        ),
        migrations.AddField(
            model_name='registro_vacaciones',
            name='estado',
            field=models.CharField(choices=[('PLAN', 'Planificado'), ('APRO', 'Aprobado'), ('EN_C', 'En Curso'), ('PAUS', 'Pausado'), ('COMP', 'Completado'), ('CANC', 'Cancelado')], default='PLAN', max_length=4),
        ),
        migrations.AddField(
            model_name='registro_vacaciones',
            name='fecha_inhabilitacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro_vacaciones',
            name='fecha_reanudacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro_vacaciones',
            name='motivo_inhabilitacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='control_vacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveIntegerField()),
                ('dias_acumulados', models.PositiveIntegerField(default=0)),
                ('dias_tomados', models.PositiveIntegerField(default=0, editable=False)),
                ('dias_pendientes', models.PositiveIntegerField(default=0, editable=False)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(default=30480815, on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones_control', to='login.empleado')),
            ],
            options={
                'verbose_name_plural': 'Controles de Vacaciones',
                'unique_together': {('empleado', 'año')},
            },
        ),
        migrations.AddField(
            model_name='registro_vacaciones',
            name='control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.control_vacaciones'),
        ),
        migrations.DeleteModel(
            name='licencia',
        ),
    ]
