# Generated by Django 5.1.7 on 2025-06-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0047_alter_permiso_asistencias_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permiso_asistencias',
            table='permiso_asistencias',
        ),
    ]
