# Generated by Django 5.1.7 on 2025-06-13 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0048_alter_permiso_asistencias_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='control_vacaciones',
            table='control_vacaciones',
        ),
        migrations.AlterModelTable(
            name='registro_vacaciones',
            table='registros_vacaciones',
        ),
    ]
