# Generated by Django 5.1.7 on 2025-06-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0049_alter_control_vacaciones_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permiso_asistencias',
            old_name='aprobado_por',
            new_name='hecho_por',
        ),
    ]
