# Generated by Django 5.1.7 on 2025-06-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0050_rename_aprobado_por_permiso_asistencias_hecho_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permiso_asistencias',
            name='hecho_por',
        ),
    ]
