# Generated by Django 5.1.7 on 2025-06-14 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0051_remove_permiso_asistencias_hecho_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control_vacaciones',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones_control', to='login.empleado'),
        ),
    ]
