# Generated by Django 5.1.7 on 2025-06-14 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0052_alter_control_vacaciones_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_vacaciones',
            name='control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_vacaciones', to='login.control_vacaciones'),
        ),
    ]
