# Generated by Django 5.1.7 on 2025-06-15 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0053_alter_registro_vacaciones_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='hijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('estudia', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='S', max_length=1)),
                ('nivel_educativo', models.CharField(blank=True, max_length=50, null=True)),
                ('discapacidad', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hijos_empleado', to='login.empleado')),
            ],
            options={
                'verbose_name': 'Hijo',
                'verbose_name_plural': 'Hijos',
                'unique_together': {('empleado', 'nombre_completo', 'fecha_nacimiento')},
            },
        ),
    ]
