# Generated by Django 5.1.7 on 2025-06-16 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0054_hijo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hijo',
            table='hijos',
        ),
    ]
