# Generated by Django 5.1.7 on 2025-06-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0055_alter_hijo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='grado_instruccion',
            field=models.CharField(blank=True, choices=[('NINGUNO', 'Ninguno'), ('PRIMARIA', 'Primaria'), ('BACHILLER', 'Secundaria'), ('TECNICO', 'Técnico Medio'), ('TSU', 'Técnico Superior Universitario (TSU)'), ('PROFESIONAL', 'Profesional'), ('ESPECIALISTA', 'Especialista'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado')], max_length=20, null=True, verbose_name='Nivel de Instrucción'),
        ),
    ]
