# Generated by Django 5.1.7 on 2025-06-16 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0056_alter_empleado_grado_instruccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARC',
            fields=[
                ('id_arc', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('total_monto_declarar', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_vacaciones', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_aguinaldos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_evaluacion', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_salarios', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.empleado')),
            ],
            options={
                'verbose_name': 'ARC',
                'verbose_name_plural': 'ARCs',
                'db_table': 'arc',
                'unique_together': {('empleado', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='DetalleARC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('monto_bruto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('porcentaje_retencion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('islr_retenido', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monto_neto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('monto_declarar', models.DecimalField(decimal_places=2, max_digits=14)),
                ('especificacion', models.CharField(default='Exento', max_length=20)),
                ('arc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='login.arc')),
            ],
            options={
                'verbose_name': 'Detalle ARC',
                'verbose_name_plural': 'Detalles ARC',
                'db_table': 'detalle_arc',
                'unique_together': {('arc', 'mes')},
            },
        ),
    ]
