# Generated by Django 5.1.7 on 2025-06-22 04:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0059_remove_usuario_rol_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arc',
            name='fecha_generacion',
        ),
        migrations.RemoveField(
            model_name='arc',
            name='total_aguinaldos',
        ),
        migrations.RemoveField(
            model_name='arc',
            name='total_evaluacion',
        ),
        migrations.RemoveField(
            model_name='arc',
            name='total_salarios',
        ),
        migrations.RemoveField(
            model_name='arc',
            name='total_vacaciones',
        ),
        migrations.RemoveField(
            model_name='detallearc',
            name='especificacion',
        ),
        migrations.RemoveField(
            model_name='detallearc',
            name='monto_neto',
        ),
        migrations.AddField(
            model_name='arc',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='arc',
            name='islr_total_retenido',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallearc',
            name='especificacion_inferior',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='detallearc',
            name='especificacion_superior',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='detallearc',
            name='nombre_mes',
            field=models.CharField(default='Enero', max_length=20),
        ),
        migrations.AlterField(
            model_name='arc',
            name='total_monto_declarar',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallearc',
            name='islr_retenido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallearc',
            name='mes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detallearc',
            name='monto_bruto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallearc',
            name='monto_declarar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detallearc',
            name='porcentaje_retencion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
